spring:
  batch:
    job:
      names: "ValidateParamJob"
#      names: "helloWorldJob"
    jdbc:
      initialize-schema: always
  datasource:
    url: jdbc:mysql://localhost:3306/testDB?serverTimezone=Asia/Seoul
    username: geon
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect